name: Deploy Hugo site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write      # Required to deploy to GitHub Pages
  id-token: write   # Required for OIDC token generation

concurrency:
  group: "pages"
  cancel-in-progress: false # Changed to false, typical for deployments

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        # Use the latest stable version of checkout
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (if stored as submodules)
          fetch-depth: 0    # Fetch all history for .GitInfo and Lastmod

      - name: Setup Hugo
        # Use a well-established Hugo setup action
        uses: peaceiris/actions-hugo@v2 # v2 is stable; consider v3 if needed
        with:
          hugo-version: 'latest'
          # extended: true # Uncomment if you need the extended version (for SASS/SCSS)

      # Optional: Setup Node.js if your build process needs it (e.g., for PostCSS, JS bundling)
      # - name: Setup Node
      #   uses: actions/setup-node@v4 # Use latest stable Node setup
      #   with:
      #     node-version: '18' # Or your required version
      #     cache: 'npm' # Or 'yarn', 'pnpm'

      # Optional: Install Node dependencies if needed
      # - name: Install dependencies
      #   run: npm ci # Or yarn install, pnpm install

      - name: Build with Hugo
        # Build site including drafts and future posts if needed for preview/testing
        # Add --baseURL flag for correct links in GitHub Pages subdirectories
        # Example: HUGO_BASEURL: ${{ steps.pages.outputs.base_url }}
        run: hugo --minify # Add other flags like --baseURL if necessary

      - name: Upload artifact
        # Use the latest version specifically designed for Pages artifacts
        uses: actions/upload-pages-artifact@v3 # <-- Key update based on recommendation
        with:
          # Upload the public directory generated by Hugo
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build # Ensure the build job completes successfully first
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        # Use the latest version of the deployment action
        uses: actions/deploy-pages@v4 # <-- Updated deployment action